USE [master]
GO
/****** Object:  Database [TP09]    Script Date: 4/10/2023 09:20:22 ******/
CREATE DATABASE [TP09]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TP09', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TP09.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TP09_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TP09_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [TP09] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TP09].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TP09] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TP09] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TP09] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TP09] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TP09] SET ARITHABORT OFF 
GO
ALTER DATABASE [TP09] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TP09] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TP09] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TP09] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TP09] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TP09] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TP09] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TP09] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TP09] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TP09] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TP09] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TP09] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TP09] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TP09] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TP09] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TP09] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TP09] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TP09] SET RECOVERY FULL 
GO
ALTER DATABASE [TP09] SET  MULTI_USER 
GO
ALTER DATABASE [TP09] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TP09] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TP09] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TP09] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TP09] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'TP09', N'ON'
GO
ALTER DATABASE [TP09] SET QUERY_STORE = OFF
GO
USE [TP09]
GO
/****** Object:  User [alumno]    Script Date: 4/10/2023 09:20:22 ******/
CREATE USER [alumno] FOR LOGIN [alumno] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[Preguntas]    Script Date: 4/10/2023 09:20:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Preguntas](
	[IdPregunta] [int] IDENTITY(1,1) NOT NULL,
	[PreguntaTexto] [varchar](150) NOT NULL,
 CONSTRAINT [PK_Preguntas] PRIMARY KEY CLUSTERED 
(
	[IdPregunta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT INTO [dbo].[Preguntas] ([PreguntaTexto]) VALUES ('¿Cuál es el nombre de tu primera mascota?');
INSERT INTO [dbo].[Preguntas] ([PreguntaTexto]) VALUES ('¿En qué ciudad nació tu madre?');
INSERT INTO [dbo].[Preguntas] ([PreguntaTexto]) VALUES ('¿Cuál es tu comida favorita?');
INSERT INTO [dbo].[Preguntas] ([PreguntaTexto]) VALUES ('¿Cuál es el nombre de tu abuelo paterno?');
/****** Object:  Table [dbo].[Usuarios]    Script Date: 4/10/2023 09:20:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[IdUsuario] [int] IDENTITY(1,1) NOT NULL,
	[NombreUsuario] [varchar](50) NOT NULL,
	[Password] [varchar](MAX) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Telefono] [varchar](20) NULL,
	[IdPregunta] [int] NOT NULL,
	[Respuesta] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD  CONSTRAINT [FK_Usuarios_Preguntas] FOREIGN KEY([IdPregunta])
REFERENCES [dbo].[Preguntas] ([IdPregunta])
GO
ALTER TABLE [dbo].[Usuarios] CHECK CONSTRAINT [FK_Usuarios_Preguntas]
GO
USE [master]
GO
ALTER DATABASE [TP09] SET  READ_WRITE  
GO
